global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    basic_auth:
      username: 'admin'
      password: 'admin'
    metrics_path: '/prometheus'
    static_configs:
      - targets: 
        - '192.168.0.6:8080' # todo Rewrite with bootJar and custome container