    
security:
  user:
    name: test
    password: test
spring:
  h2:
    console:
      enabled:true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:./db/test;MODE=PostgreSQL
logging:
  level:
    org:
      hibernate:
        SQL:debug